try {
 timeout(time: 20, unit: 'MINUTES') {
	  node('maven') {
		stage('build') {
          openshift.withCluster() {
             openshift.withProject() {
                def bld = openshift.startBuild('member-service')
                bld.untilEach {
                  return it.object().status.phase == "Running"
                }
                bld.logs('-f')
             }
          }
        }
        stage('deploy') {
          openshift.withCluster() {
            openshift.withProject() {
              def dc = openshift.selector('dc', 'member-service')
              dc.rollout().latest()
            }
          }
        }
	  }
	  node("nodejs") {
		// download and configure all common cicd stuff
        dir('cicd') {
            git "https://github.com/sbalajipune/testapp.git"
            // load groovy functions
            newman = load 'cicd/pipelines/functions/newman.groovy'
        }
		stage("Integration tests") {
              newman.runTest("cicd/member-service/tests/member-service.postman_collection.json", "cicd/member-service/tests/dev.postman_environment.json")
        }
      }
    }
} catch (err) {
 echo "in catch block"
 echo "Caught: ${err}"
 currentBuild.result = 'FAILURE'
 throw err
}